package trackie.gui;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.util.Scanner;

import trackie.Trackie;
import trackie.ui.Ui;

/** Adapts Trackie's command-processing output for JavaFX chat bubbles. */
public class TrackieGui {
    private final ByteArrayOutputStream outputBuffer = new ByteArrayOutputStream();
    private final Trackie trackie;
    private boolean isExit;

    /** Creates the GUI adapter and loads Trackie's saved tasks. */
    public TrackieGui() {
        PrintStream output = new PrintStream(outputBuffer, true, StandardCharsets.UTF_8);
        Ui ui = new Ui(new Scanner(""), output);
        this.trackie = new Trackie("data/trackie.txt", ui);
        clearOutput();
    }

    /** @return Trackie's GUI-friendly welcome message */
    public String getWelcomeMessage() {
        return "Hi! I'm Trackie, your task-tracking fox.\nReady to stay on track?";
    }

    /**
     * Processes one command and returns the response generated by Trackie.
     *
     * @param input command entered in the GUI
     * @return response text for the chat bubble
     */
    public String getResponse(String input) {
        clearOutput();
        this.isExit = !this.trackie.processCommand(input);
        return outputBuffer.toString(StandardCharsets.UTF_8).strip();
    }

    /** @return true if the most recent command asked Trackie to exit */
    public boolean isExit() {
        return this.isExit;
    }

    private void clearOutput() {
        this.outputBuffer.reset();
    }
}
